version: '2'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: test1010
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8002:80
    networks:
      backend:
        aliases:
          - laravel-app

networks:
  backend:
    name: backend-network1
